version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      DB_PASS: postgres
      DB_USER: postgres
      DB_NAME: TICKETS
    volumes:
      - ./db:/var/lib/postgresql

  back:
    build: .
    volumes:
      - .:/app
    ports:
      - "6600:6600"
    depends_on:
      - db
    env_file:
      - extra/user/local.env