version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

  back:
    build: .
    volumes:
      - .:/app
    ports:
      - "6600:6600"
    depends_on:
      - db
    env_file:
      - extra/user/local.env
    links:
      - "db:database"