# Generated by Django 2.0.5 on 2018-12-17 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(db_column='cd_event', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='OID')),
                ('timestamp', models.DateTimeField(db_column='dt_created', default=django.utils.timezone.now, verbose_name='Time Stamp')),
                ('name', models.CharField(db_column='nm_name', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(db_column='cd_ticket', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='OID')),
                ('type', models.CharField(db_column='nm_type', default='Full', max_length=20, verbose_name='Type')),
                ('timestamp', models.DateTimeField(db_column='dt_created', default=django.utils.timezone.now, verbose_name='Time Stamp')),
                ('event', models.ForeignKey(db_column='cd_event', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Events')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'tickets',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('event', 'type')},
        ),
    ]
